config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admin, controllers: {
  sessions: 'admins/sessions'
}

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get '/orders/:id' => 'orders#show'
    patch '/orders/:id' => 'orders#update'
    patch '/order_items/:id' => 'order_items#update', as: "order_items_path"
  end

  devise_for :customers, controllers: {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }

  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]
  resources :addresses, except: [:new, :show]
  get '/customers/mypage' => 'customers#show'
  get '/customers/mypage/edit' => 'customers#edit'
  patch '/customers/mypage' => 'customers#update'
  get '/customers/mypage/confirm' => 'customers#confirm'
  patch '/customers/mypage/confirm' => 'customers#quit'
  resources :cart_items, only: [:index, :create, :update]
  delete '/cart_items/:id' => 'cart_items#destroy'
  delete '/cart_items' => 'cart_items#destroy_all'
  post '/orders/confirm' => 'orders/confirm'
  get '/orders/complete' => 'orders/complete'
  resources :orders, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum is_deleted: {退会済み: true, 有効: false}

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :email, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
  validates :last_name, presence: true

  def check_price
    price = cart_items.to_a.sum { |item| item.for_check_price }
    price.to_s(:delimited, delimiter: ',')
  end

  def for_total_price
    cart_items.to_a.sum { |item| item.for_check_price }
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
    @name = @customer.last_name + @customer.first_name
  end

  def edit
    @customer = Customer.find(params[:id])
    @name = @customer.last_name + @customer.first_name
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer)
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted, :email)
  end


end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    customers_mypage_path(current_customer)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    customers_mypage_path(current_customer)
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  before_action :reject_user, only: [:create]

  def reject_user
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.is_deleted == "退会済み"
        flash[:none] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    end
  end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
    @customer = Customer.find(current_customer.id)
  end

  def edit
    @customer = Customer.find(current_customer.id)
  end

  def update
    @customer = Customer.find(current_customer.id)
    @customer.update(customer_params)
    redirect_to customers_mypage_path(current_customer.id)
  end

  def confirm
    @customer = Customer.find(current_customer.id)
  end

  def quit
    customer = Customer.find(current_customer.id)
    customer.update_attributes(is_deleted: true)

    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted, :email)
  end


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/confirm.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="col-lg-6 mx-auto mt-5">
        <h5 class="text-center font-weight-bold">本当に退会しますか？</h5>
        <p class="text-center mt-5">
          退会すると、会員登録情報や<br>
          これまでの購⼊履歴が閲覧できなくなります。<br>
          退会する場合は、「退会する」をクリックしてください。
        </p>
          <div class="row">
            <%= link_to '退会しない', customers_mypage_path(@customer.id), class: 'col-lg-3 mt-3 btn btn-sm btn-primary mx-auto' %>
            <%= link_to '退会する', customers_mypage_confirm_path(@customer.id), method: :patch, class: 'col-lg-3 mt-3 btn btn-sm btn-danger mx-auto' %>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/edit.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="mx-auto col-12">
      <h4 class="text-center col-lg-3 mt-4 mb-5 ml-3 page-title">会員情報編集</h4>

      <%= form_with model:@customer, url: {controller: 'customers', action: 'update' }, local:true do |f| %>
        <div class="field form-group row d-flex align-items-center">
          <label class="col-lg-2">氏名</label>
          <div class="col-lg-3"><%= f.text_field :last_name, class: 'form-control' %></div>
          <div class="col-lg-3"><%= f.text_field :first_name, class: 'form-control' %></div>
        </div>

        <div class="field form-group row d-flex align-items-center">
          <label class="col-lg-2">フリガナ</label>
          <div class="col-lg-3"><%= f.text_field :last_name_kana, class: 'form-control' %></div>
          <div class="col-lg-3"><%= f.text_field :first_name_kana, class: 'form-control' %></div>
        </div>

        <div class="field form-group row d-flex align-items-center">
          <label class="col-lg-2">郵便番号</label>
          <div class="col-lg-3"><%= f.text_field :postal_code, class: 'form-control' %></div>
        </div>

        <div class="field form-group row d-flex align-items-center">
          <label class="col-lg-2">住所</label>
          <div class="col-lg-6"><%= f.text_field :address, class: 'form-control' %></div>
        </div>

        <div class="field form-group row d-flex align-items-center">
          <label class="col-lg-2">電話番号</label>
          <div class="col-lg-3"><%= f.text_field :telephone_number, class: 'form-control' %></div>
        </div>

        <div class="field form-group row d-flex align-items-center">
          <label class="col-lg-2">メールアドレス</label>
          <div class="col-lg-3"><%= f.email_field :email, class: 'form-control' %></div>
        </div>

        <div class="actions btn-wrapper form-group row">
          <div class="col-lg-3 offset-2"><%= f.submit "編集内容を保存", class: 'mt-3 btn btn-success w-100' %></div>
          <div class="col-lg-2 offset-1"><%= link_to "退会する", customers_mypage_confirm_path, class: 'mt-3 btn btn-sm btn-danger w-100' %></div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-12">
      <h4 class="text-center col-lg-2 offset-1 mt-4 mb-5 page-title">マイページ</h4>
      <div class="row mb-2">
          <h4 class="col-lg-2 font-weight-bold">登録情報</h4>
          <%= link_to '編集する', customers_mypage_edit_path(@customer.id), class: 'btn btn-success w-80' %>
      </div>
       <table class="table table-hover table-bordered col-lg-7">
          <tbody>
            <tr>
              <td class="table-active" style="width:20%">氏名</td>
              <td style="width:60%"><%= @customer.last_name %> <%= @customer.first_name %></td>
            </tr>
            <tr>
              <td class="table-active">カナ</td>
              <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
            </tr>
            <tr>
              <td class="table-active">郵便番号</td>
              <td><%= @customer.postal_code %></td>
            </tr>
            <tr>
              <td class="table-active">住所</td>
              <td><%= @customer.address %></td>
            </tr>
            <tr>
              <td class="table-active">電話番号</td>
              <td><%= @customer.telephone_number %></td>
            </tr>
            <tr>
              <td class="table-active">メールアドレス</td>
              <td><%= @customer.email %></td>
            </tr>
          </tbody>
        </table>
      <div class="row mt-2">
          <h4 class="col-lg-2 font-weight-bold">配送先</h4>
          <%= link_to '一覧を見る', addresses_path, class: 'btn btn-primary w-90' %>
      </div>
      <div class="row mt-3">
          <h4 class="col-lg-2 font-weight-bold">注文履歴</h4>
          <%= link_to '一覧を見る', orders_path, class: 'btn btn-primary w-90' %>
      </div>
    </div>
  </div>
</div>