config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admin, controllers: {
  sessions: 'admins/sessions'
}

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get '/orders/:id' => 'orders#show'
    patch '/orders/:id' => 'orders#update'
    patch '/order_items/:id' => 'order_items#update', as: "order_items_path"
  end

  devise_for :customers, controllers: {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }

  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]
  resources :addresses, except: [:new, :show]
  get '/customers/mypage' => 'customers#show'
  get '/customers/mypage/edit' => 'customers#edit'
  patch '/customers/mypage' => 'customers#update'
  get '/customers/mypage/confirm' => 'customers#confirm'
  patch '/customers/mypage/confirm' => 'customers#quit'
  resources :cart_items, only: [:index, :create, :update]
  delete '/cart_items/:id' => 'cart_items#destroy'
  delete '/cart_items' => 'cart_items#destroy_all'
  post '/orders/confirm' => 'orders/confirm'
  get '/orders/complete' => 'orders/complete'
  resources :orders, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items
  has_many :order_items
  belongs_to :genre

  attachment :image

  enum is_active: {販売中: true, 販売停止中: false}


  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true

  def self.search(search)
    search ? where('genre_id LIKE ?', "%#{search}%") : all
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @price = @item.price.to_s(:delimited, delimiter: ',')
    @tax_price = (@item.price * 1.08).round(0)
    @tax_price = @tax_price.to_s(:delimited, delimiter: ',')
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_items_path
  end


  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active, :genre_id)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :item_search

  def index
    @items = Item.page(params[:page])
    @genres = Genre.all

    if params[:q]
      @search_items = @ransack.result.page(params[:page])
    elsif params[:p]
      @search_items = @ransack2.result.page(params[:page])
      @select_genre = Genre.find_by(id: params[:p].values)
    end
  end

  def item_search
    @ransack = Item.ransack(params[:q])
    @search_items = @ransack.result.page(params[:page])

    @ransack2 = Item.ransack(params[:p], search_key: :p)
    @genres = Genre.all
    @search_items = @ransack2.result.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
    @tax_price = (@item.price * 1.08).round(0)
    @tax_price = @tax_price.to_s(:delimited, delimiter: ',')

    @cart_item = CartItem.new

  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

  def search_params
    params.require(:p).permit(:genre_id_eq)
  end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<p id="notice"></p>

<div class="container">
  <div class="row">
    <div class="mx-auto col-12">
      <div class="row">
      <h4 class="mt-2 mb-2 ml-3 font-weight-bold">
        <% if params[:p] %>
        <span>◎</span><%= @select_genre.name %><span>一覧</span>
        <% else %>
        <span>◎商品一覧</sapn>
        <% end %>
      </h4>
      <span class="mt-3 mb-2">（全件<%= @search_items.count %>件）</sapn>
      </div>
        <div class="form-group">
          <%= search_form_for @ransack, url: items_path do |f| %>
          <div class="col-4 d-flex">
            <%= f.text_field :name_cont, placeholder: '商品名を入力', class: 'form-control' %>
            <%= f.submit ("検索"), class: 'ml-2 btn btn-info' %>
          </div>
          <% end %>
        </div>
        <div class="form-group">
          <%= search_form_for(@ransack2, as: :p, url: items_path) do |f| %>
          <div class="col-4 d-flex">
            <%= f.collection_select :genre_id_eq, @genres, :id, :name, {}, class: "form-control form-custom" %>
            <%= f.submit ("検索"), class: 'ml-2 btn btn-info' %>
          </div>
          <% end %>
        </div>
      <div class="row row-cols-1 row-cols-md-4">
        <% @search_items.each do |item| %>
        <div class="col mb-4">
        <div class="card h-100">
          <%= link_to item_path(item.id) do %>
            <%= attachment_image_tag item, :image, :fill, 300, 300, fallback: "no_image.jpg", class:"card-img-top"; %>
          <% end %>
          <div class="card-body">
            <h5 class="card-name"><%= link_to item.name, item_path(item.id), class: "text-dark" %></h5>
            <h5 class="genre-name"><%= item.genre.name %></h5>
            <h5 class="card-price">¥<%= item.price.to_s(:delimited, delimiter: ',') %></h5>
            <% if item.is_active == '販売中'
                css_class = "text-success"
               else
                css_class = "text-muted"
               end
            %>
            <h5 class="<%= css_class %> small"><%= item.is_active %></h5>
          </div>
        </div>
        </div>
        <% end %>
      </div>
        <%= paginate @items, theme: 'twitter-bootstrap-4' %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="mx-auto col-12">
      <div class="row">
        <div class="col-lg-6">
          <%= attachment_image_tag @item, :image, :fill, 250, 250, fallback: "no_image.jpg", class: 'mx-auto d-block mt-5' %>
        </div>
        <div class="col-lg-6 mt-5">
          <div class="row">
            <h3 class="font-weight-bold"><%= @item.name %></h3>
          </div>
          <div class="row">
            <p><%= @item.introduction %></p>
          </div>
          <div class="row mt-3">
            <h4>￥<%= @tax_price %></h4>
            <span class="mt-2">（税込）</span>
          </div>
        <%= form_with model: @cart_item, url: cart_items_path, local:true do |f| %>
          <div class="row">
            <div class="form-group d-flex">
              <%= f.select :amount, [1,2,3,4,5,6,7,8,9,10], { include_blank: "個数を選択" }, { class: "form-control form-custom mt-5" } %>
              <%= f.submit 'カートに入れる', class: 'btn btn-success mt-5 ml-3' %>
            </div>
          </div>
          <%= f.hidden_field :item_id, :value => @item.id %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>