config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :admin, controllers: {
  sessions: 'admins/sessions'
}

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    get '/orders/:id' => 'orders#show'
    patch '/orders/:id' => 'orders#update'
    patch '/order_items/:id' => 'order_items#update', as: "order_items_path"
  end

  devise_for :customers, controllers: {
    :registrations => 'customers/registrations',
    :sessions => 'customers/sessions'
  }

  root to: 'homes#top'
  get '/about' => 'homes#about'
  resources :items, only: [:index, :show]
  resources :addresses, except: [:new, :show]
  get '/customers/mypage' => 'customers#show'
  get '/customers/mypage/edit' => 'customers#edit'
  patch '/customers/mypage' => 'customers#update'
  get '/customers/mypage/confirm' => 'customers#confirm'
  patch '/customers/mypage/confirm' => 'customers#quit'
  resources :cart_items, only: [:index, :create, :update]
  delete '/cart_items/:id' => 'cart_items#destroy'
  delete '/cart_items' => 'cart_items#destroy_all'
  post '/orders/confirm' => 'orders/confirm'
  get '/orders/complete' => 'orders/complete'
  resources :orders, only: [:new, :create, :index, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container">
          <%= link_to " ながのCAKE", root_path, class: "fas fa-utensils nav-link navbar-brand text-light" %>
          <% if admin_signed_in? %>
            <div class="mt-1">
              <%= search_form_for @search, url: admin_customers_path do |f| %>
                <div><%= f.text_field :last_name_or_first_name_or_first_name_kana_or_last_name_kana_cont, placeholder: 'お客様の氏名を入力' %>
                  <%= f.button :type => "submit", style: 'border-style: none;' do %>
                    <i class='fas fa-search'></i>
                  <% end %>
                </div>
              <% end %>
            </div>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
              <label class="text-light p-1 mr-2 font-weight-bold">ようこそ、<%= current_customer.last_name %>さん！</label>
              <li class="nav-item"><%= link_to "マイページ", customers_mypage_path(current_customer), class: 'fas fa-user nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "商品一覧", items_path, class: 'fas fa-list nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "カート", cart_items_path, class: 'fas fa-shopping-cart nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %></li>
            <% elsif admin_signed_in? %>
              <li class="nav-item"><%= link_to "商品一覧", admin_items_path, class: 'nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "注文履歴一覧", admin_root_path(order_sort_id: 0), class: 'nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-light' %></li>
            <% else %>
              <li class="nav-item"><%= link_to "About", about_path, class: 'fas fa-landmark nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "商品一覧", items_path, class: 'fas fa-list nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "新規登録", new_customer_registration_path, class: 'fas fa-user-plus nav-link text-light' %></li>
              <li class="nav-item"><%= link_to "ログイン", new_customer_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %></li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-5">
      <%= yield %>
    </main>

<footer class="bg-light text-center text-lg-start">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-12 mb-md-0 mt-3">
        <h4 class="text-uppercase font-weight-bold">ながのCAKE</h4>
          <i class="fab fa-facebook-square mx-2"></i>
          <i class="fab fa-twitter-square mx-2"></i>
          <i class="fab fa-instagram mx-2"></i>
      </div>
      <div class="col-lg-3 col-md-6 mb-md-0 mt-3 text-left">
        <h6 class="text-uppercase small">企業情報</h6>
        <ul class="list-unstyled small">
          <li>History</li>
          <li>ソーシャルメディアポリシー</li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-6 mb-md-0 mt-3 text-left">
        <h6 class="text-uppercase small">ご使用に際して<h6>
        <ul class="list-unstyled small">
          <li>ご利用条件</li>
          <li>個人情報保護方針</li>
        </ul>
      </div>
    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    Copyright © NaganoCake Corporation. All rights reserved.
  </div>
</footer>
  </body>

</html>